package com.taixin.android.gateway.api;

public enum intHeader {
	MAX_CLIENTS(2),
	BROADCAST_PORT(7583),
	HEART_BEAT_PORT(7585),
	UNICAST_PORT(20000),
	UDP_MSG_LEN(1408),
	GATE_MAX_STRING_NUM(300),
	GATE_CMD_READ(0x40),
	GATE_CMD_WRITE(0x04),
	HEART_BEAT_FLAG(6),
	GATE_CMD_SEND_BROADCAST(1),
	GATE_CMD_RECV_BROADCAST(2),
	GATE_CMD_SEND_MATCH(3),
	GATE_CMD_RECV_MATCH(4),
	GATE_CMD_SEND_HEART_BEAT(5),
	GATE_CMD_RECV_HEART_BEAT(6),
	GATE_CMD_SEND_REQUEST_SERVICE_LIST(7),
	GATE_CMD_RECV_REQUEST_SERVICE_LIST(8),
	GATE_CMD_SEND_REQUEST_PLAY_ADDRESS(9),
	GATE_CMD_RECV_REQUEST_PLAY_ADDRESS(10),
	GATE_CMD_SEND_QUIT(11),
	GATE_CMD_RECV_QUIT(12),
	GATE_CMD_SEND_MODIFY_MACHINE_NAME(13),
	GATE_CMD_RECV_MODIFY_MACHINE_NAME(14),
	GATE_CMD_SEND_REQUEST_ZONE_CODE(15),
	GATE_CMD_RECV_REQUEST_ZONE_CODE(16),
	GATE_CMD_SEND_REQUEST_EPG_INFO(17),
	GATE_CMD_RECV_REQUEST_EPG_INFO(18),
	GATE_CMD_SEND_REQUEST_STOP_PLAY(19),
	GATE_CMD_RECV_REQUEST_STOP_PLAY(20),
	GATE_CMD_SEND_REQUEST_PALTFORM_INFO(21),
	GATE_CMD_RECV_REQUEST_PLATFORM_INFO(22),
	GATE_CMD_SEND_REQUEST_BOXNO(23),
	GATE_CMD_RECV_REQUEST_BOXNO(24)
	;
	
	
	private int value;
	
	private intHeader(int value){
		this.value = value;
	}
	
	public int value(){
		return value;
	}
}
